# Generated by Django 5.2.1 on 2025-05-28 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECV',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ECV')),
            ],
            options={
                'verbose_name_plural': 'ECVs',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the parameter.', max_length=50, verbose_name='Parameter name')),
                ('value', models.CharField(help_text='Value of the parameter.', max_length=150, verbose_name='Parameter value')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL of the dataset', verbose_name='URL')),
                ('start_date', models.DateField(blank=True, help_text='Start date of the data within the dataset.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Start date of the data within the dataset.', null=True)),
                ('ecvs', models.ManyToManyField(help_text='List of ECVs the associated with the dataset.', to='data_bridge_app.ecv')),
                ('filters', models.ManyToManyField(blank=True, help_text='List of filters to apply to the dataset.', related_name='filter', to='data_bridge_app.filter')),
                ('dataset_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_bridge_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('from_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_bridge_app.dataset')),
                ('to_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_dataset', to='data_bridge_app.dataset')),
                ('relationships', models.ManyToManyField(to='data_bridge_app.relationtype')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='related_datasets',
            field=models.ManyToManyField(help_text='List of related datasets.', related_name='+', through='data_bridge_app.Relationship', through_fields=('from_dataset', 'to_dataset'), to='data_bridge_app.dataset'),
        ),
    ]
