# Generated by Django 5.2.17 on 2026-08-26 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetProvider',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ECV',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ECV')),
            ],
            options={
                'verbose_name_plural': 'ECVs',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the parameter.', max_length=50, verbose_name='Parameter name')),
                ('value', models.CharField(help_text='Value of the parameter.', max_length=150, verbose_name='Parameter value')),
            ],
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechniqueCategory',
            fields=[
                ('name', models.CharField(help_text='Name of the technique category.', max_length=50, primary_key=True, serialize=False, verbose_name='Technique category name')),
            ],
        ),
        migrations.CreateModel(
            name='TechniqueSubtype',
            fields=[
                ('name', models.CharField(help_text='Name of the technique subtype.', max_length=50, primary_key=True, serialize=False, verbose_name='Technique subtype name')),
            ],
        ),
        migrations.CreateModel(
            name='TechniqueType',
            fields=[
                ('name', models.CharField(help_text='Name of the technique type.', max_length=50, primary_key=True, serialize=False, verbose_name='Technique type name')),
            ],
        ),
        migrations.CreateModel(
            name='TechniqueUse',
            fields=[
                ('name', models.CharField(help_text='Name of the technique use.', max_length=50, primary_key=True, serialize=False, verbose_name='Technique use name')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL of the dataset', verbose_name='URL')),
                ('start_date', models.DateField(blank=True, help_text='Start date of the data within the dataset.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Start date of the data within the dataset.', null=True)),
                ('dataset_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_bridge_app.datasetprovider')),
                ('ecvs', models.ManyToManyField(help_text='List of ECVs the associated with the dataset.', to='data_bridge_app.ecv')),
                ('filters', models.ManyToManyField(blank=True, help_text='List of filters to apply to the dataset.', related_name='filter', to='data_bridge_app.filter')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dataset_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_bridge_app.datasetprovider')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_pk', models.CharField()),
                ('target_object_pk', models.CharField()),
                ('description', models.TextField(blank=True)),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('relationships', models.ManyToManyField(to='data_bridge_app.relationtype')),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_bridge_app.techniquecategory')),
                ('subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_bridge_app.techniquesubtype')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_bridge_app.techniquetype')),
                ('use', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_bridge_app.techniqueuse')),
            ],
        ),
    ]
