# Generated by Django 5.2.17 on 2026-08-25 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_bridge_app",
            "0002_aicategory_aiuse_remove_dataset_related_datasets_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "dataset_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_bridge_app.datasetprovider",
                    ),
                ),
            ],
        ),
    ]
